### PR TITLE
Create flow endpoint

### PR DESCRIPTION
**Pull request by AlbertHald**
MANGLER: Ordenlig opsætning af post request der opretter flows. Lige nu er der krims krams. Anti bread

### CODE REVIEW

**Review by TSKsmiley — APPROVED** [review]
Looks very good thanks for your service

**Comment by AlbertHald** [comment]
LGWBOBIWLTSTIALGTM

**Review by BaBrixx — APPROVED** [review]
This looks very good to me thank
git-merge
s

**Comment by TSKsmiley** [comment]
lgb

https://user-images.githubusercontent.com/37146398/160990759-103ad3a0-27a5-4a6a-adb1-30fe110aea74.mp4

t

**Comment by SolarEarth37** [comment]
Luk god to mi

**Pull request merged**
